#!/bin/bash

NX_VERSION="0.2"
NX_BASE_URL="https://raw.githubusercontent.com/nixlike/nx/master"
NX_WGET=$(which wget)
export NX_ROOT="$HOME/.nx"

alias nx_ver="echo $NX_VERSION"


#Updating to the last version
function nx_up {

 #Checking if nx folder exists 
 if [ ! -d $NX_ROOT ]; then mkdir $NX_ROOT; fi 

 #Downloading from repository
 if [ -x $NX_WGET ]
 then 
  echo "Downloading artifacts"
  $NX_WGET -q -O $NX_ROOT/nxrc $NX_BASE_URL/nxrc
  $NX_WGET -q -O $NX_ROOT/nxvimrc $NX_BASE_URL/vimrc
 fi
 
 #Checking bashrc
 grep "$NX_ROOT/nxrc" ~/.bashrc  > /dev/null
 if [ $? -ne 0 ]
 then
  echo "Adding include to ~/.bashrc !!"
  echo "" >> ~/.bashrc
  echo "source $NX_ROOT/nxrc" >> ~/.bashrc
 fi

#Checking .vimrc
 which vim > /dev/null
 if [ $? == 0 ]
 then
  grep "$NX_ROOT/nxvimrc" ~/.vimrc  > /dev/null 
  if [ $? -ne 0 ]
  then
    echo "Adding include to .vimrc !!"
    echo "" >> ~/.vimrc
    echo "source $NX_ROOT/nxvimrc" >> ~/.vimrc
  fi
 fi
 echo "Updated to NX_VERSION = $NX_VERSION"
 source ~/.bashrc
}

#AWS shortcuts

alias nx_awdis="aws ec2 describe-instance-status --include-all-instances"
alias nx_awdi="aws ec2 describe-instances"
alias nx_sa="ssh -i ~/.ssh/id_rsa_nixlike_aws.pem"

#Docker aliases

alias nx_dcb="sudo docker-compose build"
alias nx_dcu="sudo docker-compose up"
alias nx_dcd="sudo docker-compose up -d"
alias nx_dcp="sudo docker-compose ps"
